import { speciesAdjustment, mroundPositive } from './epic-engine.mjs?v=112';
const CATEGORY_CONFIG=Object.freeze({troop:{capacityInput:'leadership',fillInput:'leadershipFill',capacityEach:'leadershipEach'},monster:{capacityInput:'dominance',fillInput:'dominanceFill',capacityEach:'dominanceEach'},mercenary:{capacityInput:'authority',fillInput:'authorityFill',capacityEach:'authorityEach'}});
function selectedUnits(units,ids){const s=new Set(ids??[]);return units.filter(u=>s.has(u.id));}
function specialist(u){return String(u.class||'').toUpperCase()==='SPECIALIST';}
function familyStrengthPct(u,i){const s=String(u.species||'').toUpperCase();if(s==='EPIC HUNTER')return Number(i.epicHunterStrengthPct||0);if(['BEAST','DRAGON','ELEMENTAL','GIANT'].includes(s))return Number(i.monsterStrengthPct||0);return Number(i.humanStrengthPct||0);}
export function pvpEffectiveStrengthEach(u,i){return Number(u.strengthEach||0)*(1+familyStrengthPct(u,i)/100)*(specialist(u)?2:1);}
function preservationScore(u,i,battleType,stats){const cfg=CATEGORY_CONFIG[u.category],cap=Math.max(1,Number(u[cfg.capacityEach]||1)),power=pvpEffectiveStrengthEach(u,i)/cap;if(battleType!=='pvp_single_cp')return power;const gold=Math.max(0,Number(u.goldRevivalCost||0))/cap;const powerNorm=stats.maxPower>0?power/stats.maxPower:0,costNorm=stats.maxGold>0?gold/stats.maxGold:0;return powerNorm+costNorm;}
export function calculateBattleCategory({category,units,selectedIds,inputs,battleType='pvp_unknown'}){const cfg=CATEGORY_CONFIG[category],selected=selectedUnits(units,selectedIds);if(!selected.length)return{category,selectedCount:0,totalCapacity:0,capacityPercent:0,results:[]};const maxHealthEach=Math.max(...selected.map(u=>Number(u.healthEach||0))),limit=Number(inputs[cfg.capacityInput]||0),fill=Number(inputs[cfg.fillInput]||0),sep=Number(inputs.rankSeparation||0);const stats={maxPower:Math.max(...selected.map(u=>pvpEffectiveStrengthEach(u,inputs)/Math.max(1,Number(u[cfg.capacityEach]||1)))),maxGold:Math.max(...selected.map(u=>Math.max(0,Number(u.goldRevivalCost||0))/Math.max(1,Number(u[cfg.capacityEach]||1))))};const ordered=selected.slice().sort((a,b)=>preservationScore(a,inputs,battleType,stats)-preservationScore(b,inputs,battleType,stats)||Number(a.displayOrder||0)-Number(b.displayOrder||0));const death=new Map(ordered.map((u,k)=>[u.id,k])),count=ordered.length;const interim=selected.map(u=>{const idx=death.get(u.id)||0,adj=speciesAdjustment(u.species,inputs.healthInputs),hm=1+(count-1-idx)*sep,modifier=hm+adj,cap=Number(u[cfg.capacityEach]||0),C=modifier*maxHealthEach/Number(u.healthEach||1),D=C*cap;return{u,idx,adj,cap,D,preservation:preservationScore(u,inputs,battleType,stats)}});const sumD=interim.reduce((s,r)=>s+r.D,0);const results=interim.map(r=>{const raw=sumD>0?(r.D/sumD)*(limit/r.cap)*fill:0,qty=mroundPositive(Math.max(0,raw),1);return{id:r.u.id,category,displayOrder:r.u.displayOrder,selectionKey:r.u.selectionKey,level:r.u.level,type:r.u.type,name:r.u.name,icon:r.u.icon,qty,rawQty:raw,roundTo:1,rank:r.idx+1,deathIndex:r.idx,squadHealth:(qty*r.u.healthEach)/(1+r.adj),squadStrength:pvpEffectiveStrengthEach(r.u,inputs)*qty,pvpStrengthEach:pvpEffectiveStrengthEach(r.u,inputs),specialistPvpMultiplier:specialist(r.u)?2:1,preservationScore:r.preservation,totalCapacity:r.cap*qty}});const totalCapacity=results.reduce((s,r)=>s+r.totalCapacity,0);return{category,selectedCount:selected.length,maxHealthEach,capacityLimit:limit,requestedFill:fill,totalCapacity,capacityPercent:limit?totalCapacity/limit:0,results:results.slice().sort((a,b)=>a.displayOrder-b.displayOrder)};}
export function calculateBattleStack({troops,monsters,mercenaries,selectedIds,inputs,battleType}){const troop=calculateBattleCategory({category:'troop',units:troops,selectedIds:selectedIds.troop,inputs,battleType}),monster=calculateBattleCategory({category:'monster',units:monsters,selectedIds:selectedIds.monster,inputs,battleType}),mercenary=calculateBattleCategory({category:'mercenary',units:mercenaries,selectedIds:selectedIds.mercenary,inputs,battleType});return{inputs:structuredClone(inputs),battleType,categories:{troop,monster,mercenary},totals:{leadership:troop.totalCapacity,dominance:monster.totalCapacity,authority:mercenary.totalCapacity}};}
