(() => {
const $=id=>document.getElementById(id);
let records=[],filtered=[],normData={epicMonsters:[],tinman:[]},columnSort={key:null,direction:null};
const fixedKeys=['type','chest'];
const resourceKeys=['clanWealth','gold','potion','talentReset','cityTeleport','epicTar','rareTar','commonTar','silver','wood','iron','stone','food','speedupDays','clanSpeedupDays','dragonCoins','summonsScroll','marchSpeed50'];
const plannerKeys=resourceKeys.filter(k=>k!=='clanWealth');
const labels={clanWealth:'Clan Wealth',gold:'Gold',potion:'Potion',talentReset:'Talent Reset',cityTeleport:'City Teleport',epicTar:'Epic Tar',rareTar:'Rare Tar',commonTar:'Common Tar',silver:'Silver',wood:'Wood',iron:'Iron',stone:'Stone',food:'Food',speedupDays:'Speedup (days)',clanSpeedupDays:'Clan Speedup (days)',dragonCoins:'Dragon Coins',summonsScroll:'Summons Scroll',marchSpeed50:'50% March Speed'};
const coreKeys=['gold','potion','silver','dragonCoins'],growthKeys=['commonTar','rareTar','epicTar','speedupDays','wood','iron','stone'];
const selectedRewards=new Set(),selectedPlannerResources=new Set(coreKeys),storageKey='tbtoolkit-clan-norm-profiles-v1';
let profiles=[],activeProfileId='';
let resourcePreset='core';
const isDayKey=k=>k==='speedupDays'||k==='clanSpeedupDays';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const positive=(v,f=0)=>{const n=Number(v);return Number.isFinite(n)&&n>=0?n:f;};
const whole=(v,f=0)=>Math.floor(positive(v,f));
const formatNumber=v=>Number(v||0).toLocaleString('en-US',{maximumFractionDigits:2});
const formatCompact=v=>{const n=Number(v)||0,a=Math.abs(n);if(a>=1e12)return `${(n/1e12).toLocaleString('en-US',{maximumFractionDigits:2})}T`;if(a>=1e9)return `${(n/1e9).toLocaleString('en-US',{maximumFractionDigits:2})}B`;if(a>=1e6)return `${(n/1e6).toLocaleString('en-US',{maximumFractionDigits:2})}M`;if(a>=1e3)return `${(n/1e3).toLocaleString('en-US',{maximumFractionDigits:2})}K`;return formatNumber(n);};
function formatChestValue(v){if(v===null||v===undefined||v==='')return '—';const n=Number(v);return n>10?n.toLocaleString('en-US',{maximumFractionDigits:0}):n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});}

function updateRewardButton(){const text=$('rewardFilterButtonText');if(!selectedRewards.size)text.textContent='All rewards';else if(selectedRewards.size===1)text.textContent=labels[[...selectedRewards][0]];else if(selectedRewards.size<=3)text.textContent=[...selectedRewards].map(k=>labels[k]).join(', ');else text.textContent=`${selectedRewards.size} rewards selected`;}
function populateFilters(){
  [...new Set(records.map(r=>r.type))].sort().forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;$('chestTypeFilter').appendChild(o);});
  $('rewardFilterOptions').innerHTML=resourceKeys.map(k=>`<label class="reward-option"><input type="checkbox" value="${k}"><span>${labels[k]}</span></label>`).join('');
  $('rewardFilterOptions').querySelectorAll('input').forEach(box=>box.addEventListener('change',()=>{box.checked?selectedRewards.add(box.value):selectedRewards.delete(box.value);updateRewardButton();apply();}));
}
function visibleKeys(){return selectedRewards.size?[...fixedKeys,...resourceKeys.filter(k=>selectedRewards.has(k))]:[...fixedKeys,...resourceKeys];}
function apply(){
  const q=$('chestSearch').value.trim().toLowerCase(),type=$('chestTypeFilter').value;
  filtered=records.filter(r=>(!q||`${r.type} ${r.chest}`.toLowerCase().includes(q))&&(!type||r.type===type));
  if(columnSort.key){const {key}=columnSort,dir=columnSort.direction==='desc'?-1:1;filtered.sort((a,b)=>{if(fixedKeys.includes(key))return dir*String(a[key]??'').localeCompare(String(b[key]??''),undefined,{numeric:true,sensitivity:'base'});const av=Number(a[key]),bv=Number(b[key]);if(!Number.isFinite(av))return 1;if(!Number.isFinite(bv))return -1;return dir*(av-bv)||a.chest.localeCompare(b.chest,undefined,{numeric:true});});}
  else{const sort=$('chestSort').value;if(sort==='name')filtered.sort((a,b)=>a.chest.localeCompare(b.chest));else if(sort==='type')filtered.sort((a,b)=>a.type.localeCompare(b.type)||a.chest.localeCompare(b.chest));}
  renderChestTable();
}
function renderChestTable(){
  $('visibleChestCount').textContent=filtered.length.toLocaleString();$('visibleTypeCount').textContent=new Set(filtered.map(r=>r.type)).size;$('clearChestSearch').hidden=!$('chestSearch').value;$('chestEmpty').hidden=!!filtered.length;$('chestTableShell').hidden=!filtered.length;
  const keys=visibleKeys();document.querySelector('.chest-table')?.classList.toggle('compact-reward-view',selectedRewards.size>0);$('activeRewardSummary').textContent=selectedRewards.size?`Showing selected reward columns: ${[...selectedRewards].map(k=>labels[k]).join(', ')}`:'Showing all compiled rewards';
  $('chestTableHead').innerHTML=`<tr>${keys.map(k=>{const active=columnSort.key===k,arrow=active?(columnSort.direction==='asc'?'▲':'▼'):'';return `<th class="sortable-header${active?' is-sorted':''}" data-sort-key="${k}" tabindex="0" aria-sort="${active?(columnSort.direction==='asc'?'ascending':'descending'):'none'}"><span>${k==='type'?'Type':k==='chest'?'Chest':labels[k]}</span><span class="sort-arrow">${arrow}</span></th>`;}).join('')}</tr>`;
  $('chestTableBody').innerHTML=filtered.map(r=>`<tr>${keys.map(k=>{const missing=r[k]===null||r[k]===undefined||r[k]==='',display=selectedRewards.has(k)&&missing?0:r[k],cls=[k==='type'?'type-cell':'',k==='chest'?'chest-cell':'',missing?'blank':'',isDayKey(k)?'days':'',selectedRewards.has(k)?'reward-highlight':''].filter(Boolean).join(' ');return `<td class="${cls}">${fixedKeys.includes(k)?esc(display??'—'):formatChestValue(display)}</td>`;}).join('')}</tr>`).join('');
}

function plannerPeriod(){return $('normPeriod').value==='custom'?Math.max(1,whole($('customPeriodDays').value,1)):Number($('normPeriod').value);}
function plannerState(){return {period:$('normPeriod').value,customPeriodDays:$('customPeriodDays').value,recipients:$('clanRecipients').value,resources:[...selectedPlannerResources],resourcePreset,ashenDefaultApplied:true,visibleEpics:[...document.querySelectorAll('#epicVisibilityOptions input:checked')].map(x=>x.value),epics:[...document.querySelectorAll('.epic-norm-row')].map(row=>({monster:row.dataset.monster,basis:row.querySelector('.epic-basis').value,value:row.querySelector('.epic-value').value,unit:row.querySelector('.epic-unit').value})),chestNorms:[...document.querySelectorAll('.chest-norm-row')].map(row=>({chestId:row.querySelector('.chest-norm-select').value,count:row.querySelector('.chest-norm-count').value,cadence:row.querySelector('.chest-norm-cadence').value})),tinman:{startLevel:$('tinmanStartLevel').value,summons:$('tinmanSummons').value}};}
function blankPlan(){return {period:'6',customPeriodDays:12,recipients:100,resources:[...coreKeys],resourcePreset:'core',ashenDefaultApplied:true,visibleEpics:normData.epicMonsters.filter(x=>x.monster!=='ASHEN').map(x=>x.monster),epics:[],chestNorms:[{chestId:'CRYPT|EPIC 35',count:300,cadence:6}],tinman:{startLevel:1,summons:0}};}
function makeId(){return `norm-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;}
function saveProfiles(){try{localStorage.setItem(storageKey,JSON.stringify({schemaVersion:1,activeProfileId,profiles}));}catch{}}
function savePlanner(){const profile=profiles.find(x=>x.id===activeProfileId);if(profile)profile.plan=plannerState();saveProfiles();}
function loadProfiles(){try{const data=JSON.parse(localStorage.getItem(storageKey)||'null');if(data?.profiles?.length){profiles=data.profiles;activeProfileId=data.activeProfileId||profiles[0].id;return;}}catch{}const id=makeId();profiles=[{id,name:'My Clan',plan:blankPlan()}];activeProfileId=id;saveProfiles();}
function uniqueProfileName(base,excludeId=''){let name=String(base||'Clan').trim().slice(0,60)||'Clan',n=2;while(profiles.some(x=>x.id!==excludeId&&x.name.toLowerCase()===name.toLowerCase()))name=`${String(base||'Clan').trim()||'Clan'} ${n++}`.slice(0,60);return name;}
function renderProfileSelect(){$('normProfileSelect').innerHTML=profiles.map(x=>`<option value="${esc(x.id)}" ${x.id===activeProfileId?'selected':''}>${esc(x.name)}</option>`).join('');$('removeNormProfile').disabled=profiles.length<=1;}
function presetKeys(name){return name==='core'?coreKeys:name==='growth'?growthKeys:plannerKeys;}
function renderPlannerResources(){const shown=resourcePreset?presetKeys(resourcePreset):plannerKeys;$('normResourceOptions').innerHTML=shown.map(k=>`<label><input type="checkbox" value="${k}" ${selectedPlannerResources.has(k)?'checked':''}><span>${labels[k]}</span></label>`).join('');document.querySelectorAll('[data-resource-preset]').forEach(button=>button.classList.toggle('is-active',button.dataset.resourcePreset===resourcePreset));$('normResourceOptions').querySelectorAll('input').forEach(box=>box.addEventListener('change',()=>{box.checked?selectedPlannerResources.add(box.value):selectedPlannerResources.delete(box.value);resourcePreset='';renderPlannerResources();calculatePlanner();}));}
function sortedEpics(){return [...normData.epicMonsters].sort((a,b)=>a.monster.localeCompare(b.monster));}
function renderEpicRows(saved=[]){const map=new Map(saved.map(x=>[x.monster,x]));$('epicNormRows').innerHTML=sortedEpics().map(item=>{const s=map.get(item.monster)||{},basis=s.basis||'points',unit=s.unit||'B';return `<div class="epic-norm-row" data-monster="${esc(item.monster)}"><div class="epic-event"><strong>${esc(item.monster)}</strong><small>${esc(item.event)} · every ${item.cadenceDays} days</small></div><label><span class="sr-only">Norm basis</span><select class="epic-basis"><option value="points" ${basis==='points'?'selected':''}>Points</option><option value="chests" ${basis==='chests'?'selected':''}>Chests</option></select></label><label><span class="sr-only">Norm value</span><input class="epic-value" type="number" min="0" step="any" value="${esc(s.value??0)}"></label><label><span class="sr-only">Point unit</span><select class="epic-unit"><option value="B" ${unit==='B'?'selected':''}>B</option><option value="M" ${unit==='M'?'selected':''}>M</option><option value="K" ${unit==='K'?'selected':''}>K</option></select></label><output class="epic-result">Excluded</output></div>`;}).join('');syncEpicUnits();}
function renderEpicVisibility(saved){const visible=new Set(Array.isArray(saved)?saved:sortedEpics().filter(x=>x.monster!=='ASHEN').map(x=>x.monster));$('epicVisibilityOptions').innerHTML=sortedEpics().map(x=>`<label><input type="checkbox" value="${esc(x.monster)}" ${visible.has(x.monster)?'checked':''}><span>${esc(x.monster)}</span></label>`).join('');applyEpicVisibility();}
function applyEpicVisibility(){const visible=new Set([...document.querySelectorAll('#epicVisibilityOptions input:checked')].map(x=>x.value));document.querySelectorAll('.epic-norm-row').forEach(row=>row.hidden=!visible.has(row.dataset.monster));}
function chestNormChoices(){return records.filter(r=>r.type==='CRYPT'||r.type==='CITADEL').sort((a,b)=>a.type.localeCompare(b.type)||a.chest.localeCompare(b.chest,undefined,{numeric:true}));}
function addChestNormRow(saved={chestId:'CRYPT|EPIC 35',count:0,cadence:6}){const row=document.createElement('div');row.className='chest-norm-row';const options=chestNormChoices().map(r=>{const id=`${r.type}|${r.chest}`;return `<option value="${esc(id)}" ${id===saved.chestId?'selected':''}>${esc(r.type)} · ${esc(r.chest)}</option>`;}).join('');row.innerHTML=`<label>Chest<select class="chest-norm-select">${options}</select></label><label>Completions per member<input class="chest-norm-count" type="number" min="0" step="1" value="${esc(saved.count??0)}"></label><label>Norm duration<select class="chest-norm-cadence"><option value="6" ${String(saved.cadence)==='6'?'selected':''}>6 days</option><option value="12" ${String(saved.cadence)==='12'?'selected':''}>12 days</option><option value="24" ${String(saved.cadence)==='24'?'selected':''}>24 days</option></select></label><button class="remove-chest-norm" type="button" aria-label="Remove chest requirement">Remove</button>`;$('chestNormRows').append(row);row.querySelector('.remove-chest-norm').addEventListener('click',()=>{row.remove();calculatePlanner();});}
function renderChestNorms(saved){$('chestNormRows').innerHTML='';const rows=Array.isArray(saved)&&saved.length?saved:[{chestId:'CRYPT|EPIC 35',count:300,cadence:6}];rows.forEach(addChestNormRow);}
function syncEpicUnits(){document.querySelectorAll('.epic-norm-row').forEach(row=>{const points=row.querySelector('.epic-basis').value==='points',unit=row.querySelector('.epic-unit');unit.disabled=!points;unit.title=points?'Point-value unit':'Chest quantities are whole chests';if(!points)unit.value='B';});}
function renderTinman(saved={}){const options=normData.tinman.map(x=>`<option value="${x.level}">Level ${x.level} · ${x.chestType} · ${x.killChestQuantity} chests</option>`).join('');$('tinmanStartLevel').innerHTML=options;$('tinmanStartLevel').value=String(saved?.startLevel||1);$('tinmanSummons').value=saved?.summons??0;}
function renderReferences(){$('epicReferenceRows').innerHTML=normData.epicMonsters.map(x=>`<tr><td>${esc(x.event)}</td><td>${esc(x.monster)}</td><td>${x.cadenceDays} days</td><td>${formatNumber(x.totalPoints)}</td><td>${formatNumber(x.totalChests)}</td><td>${formatNumber(x.pointsPerChest)}</td></tr>`).join('');$('tinmanReferenceRows').innerHTML=normData.tinman.map(x=>`<tr><td>${x.level}</td><td>${formatNumber(x.points)}</td><td>${esc(x.chestType)}</td><td>${formatNumber(x.killChestQuantity)}</td></tr>`).join('');}
function rewardRecord(type,chest){return records.find(r=>r.type===type&&String(r.chest).toUpperCase()===String(chest).toUpperCase());}
function renderResourceVisuals(activities,selected,totals){
  const palette=['#efb431','#66a3ff','#ef6d55','#75c991','#a884e8','#5cc8c5','#e38ac8','#9fb85b','#db8b45','#8da2b5','#d8cf70','#7c8df0'];
  $('resourceDonutCharts').innerHTML=selected.map(key=>{const parts=activities.map((a,i)=>({name:a.name,value:a.prorated*positive(a.reward?.[key]),color:palette[i%palette.length]})).filter(x=>x.value>0),total=totals[key]||0;let cursor=0;const stops=parts.map(p=>{const start=cursor,end=cursor+(p.value/total*100);cursor=end;return `${p.color} ${start}% ${end}%`;}).join(',');return `<article class="resource-donut-card"><h4>${esc(labels[key])}</h4>${total?`<div class="resource-donut" style="--donut:conic-gradient(${stops})"><span>${formatCompact(total)}<small>per member</small></span></div><div class="resource-donut-legend">${parts.map(p=>`<div><i style="--legend-color:${p.color}"></i><span>${esc(p.name)}</span><strong>${(p.value/total*100).toFixed(1)}%</strong></div>`).join('')}</div>`:'<p>No resource value</p>'}</article>`;}).join('');
  const categories=[['Epic monsters','#efb431'],['Crypts & Citadels','#66a3ff'],['Tinman','#ef6d55']];
  $('resourceCategoryChart').innerHTML=`<div class="category-legend">${categories.map(([name,color])=>`<span><i style="--legend-color:${color}"></i>${name}</span>`).join('')}</div>${selected.map(key=>{const values=categories.map(([name,color])=>({name,color,value:activities.filter(a=>a.category===name).reduce((sum,a)=>sum+a.prorated*positive(a.reward?.[key]),0)})),total=values.reduce((sum,x)=>sum+x.value,0);return `<div class="category-row"><strong>${esc(labels[key])}</strong><div class="category-bar">${values.map(x=>`<span style="width:${total?x.value/total*100:0}%;background:${x.color}" title="${esc(x.name)}: ${formatCompact(x.value)} (${total?(x.value/total*100).toFixed(1):'0.0'}%)"></span>`).join('')}</div><small>${formatCompact(total)}</small></div>`;}).join('')}`;
}
function calculatePlanner(){
  const period=plannerPeriod(),recipients=Math.max(1,whole($('clanRecipients').value,100)),contributors=recipients,activities=[];$('customPeriodField').hidden=$('normPeriod').value!=='custom';syncEpicUnits();applyEpicVisibility();
  const multipliers={B:1e9,M:1e6,K:1e3};
  document.querySelectorAll('.epic-norm-row:not([hidden])').forEach(row=>{const item=normData.epicMonsters.find(x=>x.monster===row.dataset.monster),basis=row.querySelector('.epic-basis').value,entered=positive(row.querySelector('.epic-value').value),unit=row.querySelector('.epic-unit').value,value=basis==='points'?entered*multipliers[unit]:entered,chests=basis==='points'?Math.floor(value/item.pointsPerChest):Math.floor(value),points=basis==='points'?value:Math.ceil(chests*item.pointsPerChest),actual=chests*contributors;row.querySelector('.epic-result').innerHTML=chests?`<strong>${formatNumber(chests)}</strong> from each norm<small>${formatNumber(actual)} received by every member</small>`:'Excluded';if(actual)activities.push({name:item.monster,category:'Epic monsters',cadence:item.cadenceDays,actual,prorated:actual*period/item.cadenceDays,equivalent:`${formatCompact(points)} points/contributor`,reward:rewardRecord('EPIC',item.monster)});});
  document.querySelectorAll('.chest-norm-row').forEach(row=>{const [type,...nameParts]=row.querySelector('.chest-norm-select').value.split('|'),name=nameParts.join('|'),count=whole(row.querySelector('.chest-norm-count').value),cadence=Number(row.querySelector('.chest-norm-cadence').value),actual=count*contributors;if(actual)activities.push({name:`${type} · ${name}`,category:'Crypts & Citadels',cadence,actual,prorated:actual*period/cadence,equivalent:`${formatNumber(count)} completions/member`,reward:rewardRecord(type,name)});});
  let tinmanPoints=0,tinmanChests=0;const start=Math.min(250,Math.max(1,whole($('tinmanStartLevel').value,1))),summons=Math.min(8,whole($('tinmanSummons').value));for(let i=0;i<summons;i++){const level=Math.min(250,start+i),t=normData.tinman.find(x=>x.level===level);if(!t)continue;tinmanPoints+=t.points;tinmanChests+=t.killChestQuantity;const cadence=normData.tinmanCadenceDays||6;activities.push({name:`Tinman level ${t.level}`,category:'Tinman',cadence,actual:t.killChestQuantity,prorated:t.killChestQuantity*period/cadence,equivalent:`${formatCompact(t.points)} points to defeat`,reward:rewardRecord('EVENT',`${t.chestType} TINMAN`)});}$('tinmanSummary').textContent=tinmanChests?`Levels ${start}–${Math.min(250,start+summons-1)} · ${formatNumber(tinmanChests)} chests received by every member · ${formatCompact(tinmanPoints)} points`:'No Tinmen included.';
  $('normDashboardScope').textContent=`Average resource value for ${period} day${period===1?'':'s'}.`;$('dashboardRecipients').textContent=formatNumber(recipients);$('dashboardActivities').textContent=formatNumber(activities.length);$('proratedChestTotal').textContent=formatNumber(activities.reduce((s,a)=>s+a.prorated,0));
  $('normResourceCards').innerHTML=selectedPlannerResources.size?[...selectedPlannerResources].map(key=>{const perMember=activities.reduce((sum,a)=>sum+a.prorated*positive(a.reward?.[key]),0);return `<article><small>${labels[key]}</small><strong>${formatCompact(perMember)}</strong><span>per member</span><em>${formatCompact(perMember*recipients)} clan-wide</em></article>`;}).join(''):'<p class="norm-no-resources">Choose at least one resource above to display resource totals.</p>';
  const selected=[...selectedPlannerResources],totals=Object.fromEntries(selected.map(k=>[k,activities.reduce((sum,a)=>sum+a.prorated*positive(a.reward?.[k]),0)]));renderResourceVisuals(activities,selected,totals);$('normBreakdownHead').innerHTML=`<tr><th>Event or activity</th>${selected.map(k=>`<th>${esc(labels[k])}<small>amount · share</small></th>`).join('')}</tr>`;$('normBreakdownRows').innerHTML=activities.length?activities.map(a=>`<tr><td><strong>${esc(a.name)}</strong><small>${esc(a.equivalent)}</small></td>${selected.map(k=>{const amount=a.prorated*positive(a.reward?.[k]),pct=totals[k]?amount/totals[k]*100:0;return `<td class="resource-contribution"><strong>${amount?formatCompact(amount):'—'}</strong><small>${amount?`${pct.toFixed(1)}%`:'0%'}</small></td>`;}).join('')}</tr>`).join('')+`<tr class="norm-total-row"><td>Total per member</td>${selected.map(k=>`<td>${formatCompact(totals[k])}<small>100%</small></td>`).join('')}</tr>`:`<tr><td colspan="${1+selected.length}" class="norm-empty-row">Enter a norm above to include it in the plan.</td></tr>`;savePlanner();
}
function restorePlanner(saved=blankPlan()){$('normPeriod').value=saved.period||'6';$('customPeriodDays').value=saved.customPeriodDays||12;$('clanRecipients').value=saved.recipients||saved.contributors||100;selectedPlannerResources.clear();const savedResources=(saved.resources||coreKeys).filter(k=>plannerKeys.includes(k));savedResources.forEach(k=>selectedPlannerResources.add(k));const same=keys=>keys.length===savedResources.length&&keys.every(k=>selectedPlannerResources.has(k));resourcePreset=saved.resourcePreset||(same(coreKeys)?'core':same(growthKeys)?'growth':same(plannerKeys)?'all':'');}
function openProfile(id){const profile=profiles.find(x=>x.id===id)||profiles[0],plan=profile.plan||blankPlan();if(!plan.ashenDefaultApplied){plan.visibleEpics=(plan.visibleEpics||sortedEpics().map(x=>x.monster)).filter(x=>x!=='ASHEN');plan.ashenDefaultApplied=true;}activeProfileId=profile.id;renderEpicRows(plan.epics);renderEpicVisibility(plan.visibleEpics);const migratedChestNorms=plan.chestNorms||(plan.crypt?[{chestId:`CRYPT|${plan.crypt.chest||'EPIC 35'}`,count:plan.crypt.count??300,cadence:plan.crypt.cadence||6}]:null);renderChestNorms(migratedChestNorms);renderTinman(plan.tinman);restorePlanner(plan);renderPlannerResources();renderProfileSelect();wireValueNavigation();calculatePlanner();}
function profileAction(kind){const current=profiles.find(x=>x.id===activeProfileId);if(kind==='new'){const name=prompt('New clan profile name:','New Clan');if(!name)return;const profile={id:makeId(),name:uniqueProfileName(name),plan:blankPlan()};profiles.push(profile);openProfile(profile.id);}else if(kind==='duplicate'){const profile={id:makeId(),name:uniqueProfileName(`${current.name} Copy`),plan:structuredClone(plannerState())};profiles.push(profile);openProfile(profile.id);}else if(kind==='rename'){const name=prompt('Rename clan profile:',current.name)?.trim();if(name){current.name=uniqueProfileName(name,current.id);renderProfileSelect();saveProfiles();}}else if(kind==='remove'&&profiles.length>1&&confirm(`Remove “${current.name}” from this browser?`)){profiles=profiles.filter(x=>x.id!==activeProfileId);openProfile(profiles[0].id);}saveProfiles();}
function safeFileName(name){return `${String(name||'clan-norms').trim().replace(/[^a-z0-9._-]+/gi,'-').replace(/^-+|-+$/g,'')||'clan-norms'}.norms`;}
function exportProfile(){savePlanner();const profile=profiles.find(x=>x.id===activeProfileId),blob=new Blob([JSON.stringify({format:'tbtoolkit-norms',schemaVersion:1,kind:'clan-norm-profile',exportedAt:new Date().toISOString(),profile:{name:profile.name,plan:profile.plan}},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=safeFileName(profile.name);a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
async function importProfile(file){if(!file)return;try{if(file.size>1_000_000)throw new Error('The file is larger than 1 MB.');const data=JSON.parse(await file.text());if(data?.format!=='tbtoolkit-norms'||data?.kind!=='clan-norm-profile'||!data?.profile?.plan)throw new Error('This is not a valid TB Toolkit .norms file.');const profile={id:makeId(),name:uniqueProfileName(data.profile.name||'Imported Clan'),plan:data.profile.plan};profiles.push(profile);openProfile(profile.id);saveProfiles();}catch(error){alert(error.message||'The .norms file could not be imported.');}finally{$('normsFileInput').value='';}}
function wireValueNavigation(){document.querySelectorAll('.epic-value').forEach((input,index,list)=>input.addEventListener('keydown',event=>{if(event.key!=='Enter'&&event.key!=='Tab')return;if(event.key==='Tab'&&event.shiftKey)return;const next=list[index+1];if(next){event.preventDefault();next.focus();next.select();}}));}
function normalizeEpicValue(input){const row=input.closest('.epic-norm-row'),unit=row?.querySelector('.epic-unit');if(!row||row.querySelector('.epic-basis').value!=='points')return;const value=positive(input.value);if(value>0&&value<1&&unit.value==='B'){input.value=String(value*1000);unit.value='M';}else if(value>0&&value<1&&unit.value==='M'){input.value=String(value*1000);unit.value='K';}}
function initPlanner(){loadProfiles();renderReferences();openProfile(activeProfileId);document.querySelector('.norm-layout').addEventListener('input',calculatePlanner);document.querySelector('.norm-layout').addEventListener('change',calculatePlanner);document.querySelector('.norm-layout').addEventListener('focusin',event=>{if(event.target.matches('input:not([type="checkbox"]):not([type="file"])'))event.target.select();});document.querySelector('.norm-layout').addEventListener('focusout',event=>{if(event.target.classList.contains('epic-value')){normalizeEpicValue(event.target);calculatePlanner();}});$('normProfileSelect').addEventListener('change',event=>{savePlanner();openProfile(event.target.value);});$('newNormProfile').addEventListener('click',()=>profileAction('new'));$('duplicateNormProfile').addEventListener('click',()=>profileAction('duplicate'));$('renameNormProfile').addEventListener('click',()=>profileAction('rename'));$('removeNormProfile').addEventListener('click',()=>profileAction('remove'));$('exportNormProfile').addEventListener('click',exportProfile);$('importNormProfile').addEventListener('click',()=>{$('normsFileInput').value='';$('normsFileInput').click();});$('normsFileInput').addEventListener('change',()=>importProfile($('normsFileInput').files?.[0]));$('addChestNorm').addEventListener('click',()=>{addChestNormRow();calculatePlanner();});$('showAllEpics').addEventListener('click',()=>{document.querySelectorAll('#epicVisibilityOptions input').forEach(x=>x.checked=true);calculatePlanner();});$('hideAllEpics').addEventListener('click',()=>{document.querySelectorAll('#epicVisibilityOptions input').forEach(x=>x.checked=false);calculatePlanner();});document.querySelectorAll('[data-resource-preset]').forEach(button=>button.addEventListener('click',()=>{resourcePreset=button.dataset.resourcePreset;selectedPlannerResources.clear();presetKeys(resourcePreset).forEach(k=>selectedPlannerResources.add(k));renderPlannerResources();calculatePlanner();}));calculatePlanner();}
function resetChestFilters(){$('chestSearch').value='';$('chestTypeFilter').value='';$('chestSort').value='source';columnSort={key:null,direction:null};selectedRewards.clear();$('rewardFilterOptions').querySelectorAll('input').forEach(b=>b.checked=false);updateRewardButton();apply();}
function activateColumnSort(th){const key=th?.dataset?.sortKey;if(!key)return;columnSort=columnSort.key===key?{key,direction:columnSort.direction==='asc'?'desc':'asc'}:{key,direction:'asc'};apply();}
async function init(){try{const [chestRes,normRes]=await Promise.all([fetch('data/chest-data.json',{cache:'no-store'}),fetch('data/norm-planner-data.json',{cache:'no-store'})]);if(!chestRes.ok||!normRes.ok)throw new Error('Planner data could not be loaded.');records=(await chestRes.json()).records||[];normData=await normRes.json();populateFilters();apply();initPlanner();}catch(err){console.error(err);$('epicNormRows').innerHTML='<p class="norm-load-error">Planner data could not be loaded. Refresh the page and try again.</p>';}}
$('chestSearch').addEventListener('input',apply);$('chestTypeFilter').addEventListener('change',apply);$('chestSort').addEventListener('change',()=>{columnSort={key:null,direction:null};apply();});$('chestTableHead').addEventListener('click',e=>activateColumnSort(e.target.closest('.sortable-header')));$('chestTableHead').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activateColumnSort(e.target.closest('.sortable-header'));}});$('rewardFilterButton').addEventListener('click',()=>{const menu=$('rewardFilterMenu'),open=menu.hidden;menu.hidden=!open;$('rewardFilterButton').setAttribute('aria-expanded',String(open));});$('selectAllRewards').addEventListener('click',()=>{resourceKeys.forEach(k=>selectedRewards.add(k));$('rewardFilterOptions').querySelectorAll('input').forEach(b=>b.checked=true);updateRewardButton();apply();});$('clearAllRewards').addEventListener('click',()=>{selectedRewards.clear();$('rewardFilterOptions').querySelectorAll('input').forEach(b=>b.checked=false);updateRewardButton();apply();});document.addEventListener('pointerdown',e=>{const menu=$('rewardFilterMenu'),button=$('rewardFilterButton');if(!menu.hidden&&!menu.contains(e.target)&&!button.contains(e.target)){menu.hidden=true;button.setAttribute('aria-expanded','false');}});$('clearChestSearch').addEventListener('click',()=>{$('chestSearch').value='';apply();$('chestSearch').focus();});$('resetChestFilters').addEventListener('click',resetChestFilters);init();
})();
