(() => {
const $=id=>document.getElementById(id);
let records=[],filtered=[],normData={epicMonsters:[],tinman:[]},columnSort={key:null,direction:null};
const fixedKeys=['type','chest'];
const resourceKeys=['clanWealth','gold','potion','talentReset','cityTeleport','epicTar','rareTar','commonTar','silver','wood','iron','stone','food','speedupDays','clanSpeedupDays','dragonCoins','summonsScroll','marchSpeed50'];
const plannerKeys=resourceKeys.filter(k=>k!=='clanWealth');
const labels={clanWealth:'Clan Wealth',gold:'Gold',potion:'Potion',talentReset:'Talent Reset',cityTeleport:'City Teleport',epicTar:'Epic Tar',rareTar:'Rare Tar',commonTar:'Common Tar',silver:'Silver',wood:'Wood',iron:'Iron',stone:'Stone',food:'Food',speedupDays:'Speedup (days)',clanSpeedupDays:'Clan Speedup (days)',dragonCoins:'Dragon Coins',summonsScroll:'Summons Scroll',marchSpeed50:'50% March Speed'};
const coreKeys=['gold','potion','silver','dragonCoins'],growthKeys=['commonTar','rareTar','epicTar','speedupDays','wood','iron','stone'];
const epicEfficiencyDefaults={ARACHNE:43,ARCANOMANCER:80,ARMAGEDDON:102,ASHEN:129,BASILISK:105,BRIAREUS:85,CHIMERA:40,DOOMSDAY:34,FENRIR:22,HELLFORGE:100,JORMUNGANDR:31,'SHADOW CITY':760};
const defaultHiddenEpics=new Set(['ASHEN','CHIMERA']);
const selectedRewards=new Set(),selectedPlannerResources=new Set(coreKeys),storageKey='tbtoolkit-clan-norm-profiles-v1';
let profiles=[],activeProfileId='';
let resourcePreset='core';
let allResourceSelection=new Set(plannerKeys);
const isDayKey=k=>k==='speedupDays'||k==='clanSpeedupDays';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const positive=(v,f=0)=>{const n=Number(v);return Number.isFinite(n)&&n>=0?n:f;};
const whole=(v,f=0)=>Math.floor(positive(v,f));
const formatNumber=v=>Number(v||0).toLocaleString('en-US',{maximumFractionDigits:2});
const formatCompact=v=>{const n=Number(v)||0,a=Math.abs(n);if(a>=1e12)return `${(n/1e12).toLocaleString('en-US',{maximumFractionDigits:2})}T`;if(a>=1e9)return `${(n/1e9).toLocaleString('en-US',{maximumFractionDigits:2})}B`;if(a>=1e6)return `${(n/1e6).toLocaleString('en-US',{maximumFractionDigits:2})}M`;if(a>=1e3)return `${(n/1e3).toLocaleString('en-US',{maximumFractionDigits:2})}K`;return formatNumber(n);};
function formatChestValue(v){if(v===null||v===undefined||v==='')return '—';const n=Number(v);return n>10?n.toLocaleString('en-US',{maximumFractionDigits:0}):n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});}

function updateRewardButton(){const text=$('rewardFilterButtonText');if(!selectedRewards.size)text.textContent='All rewards';else if(selectedRewards.size===1)text.textContent=labels[[...selectedRewards][0]];else if(selectedRewards.size<=3)text.textContent=[...selectedRewards].map(k=>labels[k]).join(', ');else text.textContent=`${selectedRewards.size} rewards selected`;}
function populateFilters(){
  [...new Set(records.map(r=>r.type))].sort().forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;$('chestTypeFilter').appendChild(o);});
  $('rewardFilterOptions').innerHTML=resourceKeys.map(k=>`<label class="reward-option"><input type="checkbox" value="${k}"><span>${labels[k]}</span></label>`).join('');
  $('rewardFilterOptions').querySelectorAll('input').forEach(box=>box.addEventListener('change',()=>{box.checked?selectedRewards.add(box.value):selectedRewards.delete(box.value);updateRewardButton();apply();}));
}
function visibleKeys(){return selectedRewards.size?[...fixedKeys,...resourceKeys.filter(k=>selectedRewards.has(k))]:[...fixedKeys,...resourceKeys];}
function apply(){
  const q=$('chestSearch').value.trim().toLowerCase(),type=$('chestTypeFilter').value;
  filtered=records.filter(r=>(!q||`${r.type} ${r.chest}`.toLowerCase().includes(q))&&(!type||r.type===type));
  if(columnSort.key){const {key}=columnSort,dir=columnSort.direction==='desc'?-1:1;filtered.sort((a,b)=>{if(fixedKeys.includes(key))return dir*String(a[key]??'').localeCompare(String(b[key]??''),undefined,{numeric:true,sensitivity:'base'});const av=Number(a[key]),bv=Number(b[key]);if(!Number.isFinite(av))return 1;if(!Number.isFinite(bv))return -1;return dir*(av-bv)||a.chest.localeCompare(b.chest,undefined,{numeric:true});});}
  else{const sort=$('chestSort').value;if(sort==='name')filtered.sort((a,b)=>a.chest.localeCompare(b.chest));else if(sort==='type')filtered.sort((a,b)=>a.type.localeCompare(b.type)||a.chest.localeCompare(b.chest));}
  renderChestTable();
}
function renderChestTable(){
  $('visibleChestCount').textContent=filtered.length.toLocaleString();$('visibleTypeCount').textContent=new Set(filtered.map(r=>r.type)).size;$('clearChestSearch').hidden=!$('chestSearch').value;$('chestEmpty').hidden=!!filtered.length;$('chestTableShell').hidden=!filtered.length;
  const keys=visibleKeys();document.querySelector('.chest-table')?.classList.toggle('compact-reward-view',selectedRewards.size>0);$('activeRewardSummary').textContent=selectedRewards.size?`Showing selected reward columns: ${[...selectedRewards].map(k=>labels[k]).join(', ')}`:'Showing all compiled rewards';
  $('chestTableHead').innerHTML=`<tr>${keys.map(k=>{const active=columnSort.key===k,arrow=active?(columnSort.direction==='asc'?'▲':'▼'):'';return `<th class="sortable-header${active?' is-sorted':''}" data-sort-key="${k}" tabindex="0" aria-sort="${active?(columnSort.direction==='asc'?'ascending':'descending'):'none'}"><span>${k==='type'?'Type':k==='chest'?'Chest':labels[k]}</span><span class="sort-arrow">${arrow}</span></th>`;}).join('')}</tr>`;
  $('chestTableBody').innerHTML=filtered.map(r=>`<tr>${keys.map(k=>{const missing=r[k]===null||r[k]===undefined||r[k]==='',display=selectedRewards.has(k)&&missing?0:r[k],cls=[k==='type'?'type-cell':'',k==='chest'?'chest-cell':'',missing?'blank':'',isDayKey(k)?'days':'',selectedRewards.has(k)?'reward-highlight':''].filter(Boolean).join(' ');return `<td class="${cls}">${fixedKeys.includes(k)?esc(display??'—'):formatChestValue(display)}</td>`;}).join('')}</tr>`).join('');
}

function plannerPeriod(){return $('normPeriod').value==='custom'?Math.max(1,whole($('customPeriodDays').value,1)):Number($('normPeriod').value);}
function plannerState(){return {period:$('normPeriod').value,customPeriodDays:$('customPeriodDays').value,recipients:$('clanRecipients').value,resources:[...selectedPlannerResources],allResources:[...allResourceSelection],resourcePreset,goldEconomicsEnabled:$('enableGoldEconomics').checked,goldEconomicsSort:$('goldEconomicsSort').value,defaultHiddenEpicsApplied:true,visibleEpics:[...document.querySelectorAll('#epicVisibilityOptions input:checked')].map(x=>x.value),epics:[...document.querySelectorAll('.epic-norm-row')].map(row=>({monster:row.dataset.monster,basis:row.querySelector('.epic-basis').checked?'points':'chests',value:row.querySelector('.epic-value').value,unit:row.querySelector('.epic-unit').value,pointsPerFullGoldRevive:row.querySelector('.epic-points-revive').value,goldRevivePct:row.querySelector('.epic-gold-pct').value})),chestNorms:[...document.querySelectorAll('.chest-norm-row')].map(row=>({chestId:row.querySelector('.chest-norm-select').value,count:row.querySelector('.chest-norm-count').value,cadence:row.querySelector('.chest-norm-cadence').value})),tinman:{startLevel:$('tinmanStartLevel').value,summons:$('tinmanSummons').value}};}
function blankPlan(){return {period:'6',customPeriodDays:12,recipients:100,resources:[...coreKeys],allResources:[...plannerKeys],resourcePreset:'core',goldEconomicsEnabled:false,goldEconomicsSort:'profit',defaultHiddenEpicsApplied:true,visibleEpics:normData.epicMonsters.filter(x=>!defaultHiddenEpics.has(x.monster)).map(x=>x.monster),epics:[],chestNorms:[{chestId:'CRYPT|EPIC 35',count:300,cadence:6}],tinman:{startLevel:1,summons:0}};}
function makeId(){return `norm-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;}
function saveProfiles(){try{localStorage.setItem(storageKey,JSON.stringify({schemaVersion:1,activeProfileId,profiles}));}catch{}}
function savePlanner(){const profile=profiles.find(x=>x.id===activeProfileId);if(profile)profile.plan=plannerState();saveProfiles();}
function loadProfiles(){try{const data=JSON.parse(localStorage.getItem(storageKey)||'null');if(data?.profiles?.length){profiles=data.profiles;activeProfileId=data.activeProfileId||profiles[0].id;return;}}catch{}const id=makeId();profiles=[{id,name:'My Clan',plan:blankPlan()}];activeProfileId=id;saveProfiles();}
function uniqueProfileName(base,excludeId=''){let name=String(base||'Clan').trim().slice(0,60)||'Clan',n=2;while(profiles.some(x=>x.id!==excludeId&&x.name.toLowerCase()===name.toLowerCase()))name=`${String(base||'Clan').trim()||'Clan'} ${n++}`.slice(0,60);return name;}
function renderProfileSelect(){$('normProfileSelect').innerHTML=profiles.map(x=>`<option value="${esc(x.id)}" ${x.id===activeProfileId?'selected':''}>${esc(x.name)}</option>`).join('');$('removeNormProfile').disabled=profiles.length<=1;}
function presetKeys(name){return name==='core'?coreKeys:name==='growth'?growthKeys:plannerKeys;}
function renderPlannerResources(){const shown=presetKeys(resourcePreset);$('normResourceOptions').innerHTML=shown.map(k=>`<label><input type="checkbox" value="${k}" ${selectedPlannerResources.has(k)?'checked':''}><span>${labels[k]}</span></label>`).join('');document.querySelectorAll('[data-resource-preset]').forEach(button=>button.classList.toggle('is-active',button.dataset.resourcePreset===resourcePreset));$('normResourceOptions').querySelectorAll('input').forEach(box=>box.addEventListener('change',()=>{box.checked?selectedPlannerResources.add(box.value):selectedPlannerResources.delete(box.value);if(resourcePreset==='all')allResourceSelection=new Set(selectedPlannerResources);calculatePlanner();}));}
function sortedEpics(){return [...normData.epicMonsters].sort((a,b)=>a.monster.localeCompare(b.monster));}
function renderEpicRows(saved=[]){const map=new Map(saved.map(x=>[x.monster,x])),colors=permanentActivityColors();$('epicNormRows').innerHTML=sortedEpics().map(item=>{const s=map.get(item.monster)||{},basis=s.basis||'points',unit=s.unit||'B',pct=[0,50,100].includes(whole(s.goldRevivePct,100))?whole(s.goldRevivePct,100):100,legacyRatio=parseCompactAmount(s.fullGoldRevive)>0?parseCompactAmount(s.pointsPerAttack,1e6)/parseCompactAmount(s.fullGoldRevive):0,ratio=s.pointsPerFullGoldRevive??(legacyRatio||epicEfficiencyDefaults[item.monster]||'');return `<div class="epic-norm-row" data-monster="${esc(item.monster)}" style="--activity-color:${colors.get(item.monster)}"><div class="epic-event"><strong>${esc(item.monster)}</strong><small>${esc(item.event)} · every ${item.cadenceDays} days</small></div><label class="epic-value-field"><input class="epic-value" aria-label="${esc(item.monster)} norm value" type="number" min="0" step="any" value="${esc(s.value??0)}"><span class="norm-value-unit">${esc(basis==='points'?unit:'chests')}</span></label><label class="epic-unit-field"><select class="epic-unit" aria-label="${esc(item.monster)} point unit"><option value="B" ${unit==='B'?'selected':''}>B</option><option value="M" ${unit==='M'?'selected':''}>M</option><option value="K" ${unit==='K'?'selected':''}>K</option></select></label><label class="epic-basis-field"><span class="epic-basis-switch"><input class="epic-basis" type="checkbox" role="switch" aria-label="${esc(item.monster)} norm by points" ${basis==='points'?'checked':''}><i></i></span><span class="basis-mode">Points</span></label><label class="epic-economics-column compact-value"><input class="epic-points-revive" aria-label="${esc(item.monster)} Epic points per full gold revive" inputmode="decimal" placeholder="e.g. 75" type="text" value="${esc(ratio)}"></label><div class="epic-economics-column gold-pct-options" role="group" aria-label="${esc(item.monster)} gold revive percentage"><input class="epic-gold-pct" type="hidden" value="${pct}">${[0,50,100].map(value=>`<button class="${value===pct?'is-active':''}" data-gold-pct="${value}" type="button">${value}%</button>`).join('')}</div><output class="epic-result">Excluded</output></div>`;}).join('');syncEpicUnits();}
function renderEpicVisibility(saved){const visible=new Set(Array.isArray(saved)?saved:sortedEpics().filter(x=>!defaultHiddenEpics.has(x.monster)).map(x=>x.monster));$('epicVisibilityOptions').innerHTML=sortedEpics().map(x=>`<label><input type="checkbox" value="${esc(x.monster)}" ${visible.has(x.monster)?'checked':''}><span>${esc(x.monster)}</span></label>`).join('');applyEpicVisibility();}
function applyEpicVisibility(){const visible=new Set([...document.querySelectorAll('#epicVisibilityOptions input:checked')].map(x=>x.value));document.querySelectorAll('.epic-norm-row').forEach(row=>row.hidden=!visible.has(row.dataset.monster));}
function chestNormChoices(){return records.filter(r=>r.type==='CRYPT'||r.type==='CITADEL').sort((a,b)=>a.type.localeCompare(b.type)||a.chest.localeCompare(b.chest,undefined,{numeric:true}));}
function addChestNormRow(saved={chestId:'CRYPT|EPIC 35',count:0,cadence:6}){const row=document.createElement('div');row.className='chest-norm-row';const options=chestNormChoices().map(r=>{const id=`${r.type}|${r.chest}`;return `<option value="${esc(id)}" ${id===saved.chestId?'selected':''}>${esc(r.type)} · ${esc(r.chest)}</option>`;}).join('');row.innerHTML=`<label>Chest<select class="chest-norm-select">${options}</select></label><label>Completions per member<input class="chest-norm-count" type="number" min="0" step="1" value="${esc(saved.count??0)}"></label><label>Norm duration<select class="chest-norm-cadence"><option value="6" ${String(saved.cadence)==='6'?'selected':''}>6 days</option><option value="12" ${String(saved.cadence)==='12'?'selected':''}>12 days</option><option value="24" ${String(saved.cadence)==='24'?'selected':''}>24 days</option></select></label><button class="remove-chest-norm" type="button" aria-label="Remove chest requirement">Remove</button>`;$('chestNormRows').append(row);row.querySelector('.remove-chest-norm').addEventListener('click',()=>{row.remove();calculatePlanner();});}
function renderChestNorms(saved){$('chestNormRows').innerHTML='';const rows=Array.isArray(saved)&&saved.length?saved:[{chestId:'CRYPT|EPIC 35',count:300,cadence:6}];rows.forEach(addChestNormRow);}
function syncEpicUnits(){document.querySelectorAll('.epic-norm-row').forEach(row=>{const points=row.querySelector('.epic-basis').checked,unit=row.querySelector('.epic-unit'),unitField=unit.closest('label'),value=row.querySelector('.epic-value'),display=String(value.value||0).slice(0,5);unitField.classList.toggle('is-hidden',!points);unitField.setAttribute('aria-hidden',String(!points));unit.disabled=!points;unit.title='Point-value unit';value.step=points?'any':'1';value.closest('.epic-value-field').style.setProperty('--norm-chars',String(Math.max(1,display.length)));row.querySelector('.basis-mode').textContent=points?'Points':'Chests';row.querySelector('.norm-value-unit').textContent=points?unit.value:'chests';});}
function syncGoldEconomics(){const enabled=$('enableGoldEconomics').checked;$('epicNormActivityBody').classList.toggle('gold-economics-enabled',enabled);$('goldEconomicsDashboard').hidden=!enabled;$('goldEconomicsData').hidden=!enabled;}
function parseCompactAmount(raw,defaultMultiplier=1){const match=String(raw??'').trim().replace(/,/g,'').match(/^([0-9]*\.?[0-9]+)\s*([KMBT])?$/i);if(!match)return 0;const multipliers={K:1e3,M:1e6,B:1e9,T:1e12};return positive(match[1])*(match[2]?multipliers[match[2].toUpperCase()]:defaultMultiplier);}
function renderTinman(saved={}){const options=normData.tinman.map(x=>`<option value="${x.level}">Level ${x.level} · ${x.chestType} · ${x.killChestQuantity} chests</option>`).join('');$('tinmanStartLevel').innerHTML=options;$('tinmanStartLevel').value=String(saved?.startLevel||1);$('tinmanSummons').value=saved?.summons??0;}
function renderReferences(){$('epicReferenceRows').innerHTML=normData.epicMonsters.map(x=>`<tr><td>${esc(x.event)}</td><td>${esc(x.monster)}</td><td>${x.cadenceDays} days</td><td>${formatNumber(x.totalPoints)}</td><td>${formatNumber(x.totalChests)}</td><td>${formatNumber(x.pointsPerChest)}</td></tr>`).join('');$('tinmanReferenceRows').innerHTML=normData.tinman.map(x=>`<tr><td>${x.level}</td><td>${formatNumber(x.points)}</td><td>${esc(x.chestType)}</td><td>${formatNumber(x.killChestQuantity)}</td></tr>`).join('');}
function rewardRecord(type,chest){return records.find(r=>r.type===type&&String(r.chest).toUpperCase()===String(chest).toUpperCase());}
function permanentActivityColors(){const names=[...new Set([...normData.epicMonsters.map(x=>x.monster),...records.filter(x=>x.type==='CRYPT'||x.type==='CITADEL').map(x=>`${x.type} · ${x.chest}`),'Tinman'])].sort((a,b)=>a.localeCompare(b));return new Map(names.map((name,index)=>{const hue=Math.round(index*137.508)%360,saturation=68+(index%3)*5,light=52+(index%2)*15;return [name,`hsl(${hue} ${saturation}% ${light}%)`];}));}
function activityLabel(name){return String(name).toLowerCase().replace(/(^|[\s·/-])([a-z])/g,(_,space,letter)=>space+letter.toUpperCase());}
function donutSvg(rawParts,total,colorMap){
  const grouped=new Map();rawParts.forEach(part=>{const name=part.category==='Tinman'?'Tinman':part.name;grouped.set(name,(grouped.get(name)||0)+part.value);});const parts=[...grouped].map(([name,value])=>({name,value,color:colorMap.get(name)})).sort((a,b)=>b.value-a.value);
  let cursor=0;const cx=180,cy=210,r=72;const rings=[],callouts=[],percentages=[];
  for(const part of parts){const pct=part.value/total*100,mid=cursor+pct/2,deg=mid*3.6-90,angle=deg*Math.PI/180,flip=deg>90&&deg<270,lineStart=91,lineEnd=103,labelRadius=108,x1=cx+Math.cos(angle)*lineStart,y1=cy+Math.sin(angle)*lineStart,x2=cx+Math.cos(angle)*lineEnd,y2=cy+Math.sin(angle)*lineEnd,tx=cx+Math.cos(angle)*labelRadius,ty=cy+Math.sin(angle)*labelRadius,label=`${activityLabel(part.name)}${pct<4?` · ${pct.toFixed(1)}%`:''}`;
    rings.push(`<circle cx="${cx}" cy="${cy}" r="${r}" pathLength="100" fill="none" stroke="${part.color}" stroke-width="34" stroke-dasharray="${pct} ${100-pct}" stroke-dashoffset="${-cursor}" transform="rotate(-90 ${cx} ${cy})"><title>${esc(part.name)}: ${formatCompact(part.value)} (${pct.toFixed(1)}%)</title></circle>`);
    callouts.push(`<line x1="${x1.toFixed(1)}" y1="${y1.toFixed(1)}" x2="${x2.toFixed(1)}" y2="${y2.toFixed(1)}" stroke="${part.color}"/><text class="donut-label" style="fill:${part.color}" x="${tx.toFixed(1)}" y="${ty.toFixed(1)}" text-anchor="${flip?'end':'start'}" dominant-baseline="middle" transform="rotate(${(flip?deg+180:deg).toFixed(1)} ${tx.toFixed(1)} ${ty.toFixed(1)})">${esc(label)}</text>`);
    if(pct>=4){const px=cx+Math.cos(angle)*r,py=cy+Math.sin(angle)*r;percentages.push(`<text class="slice-percent" x="${px.toFixed(1)}" y="${py.toFixed(1)}" text-anchor="middle" dominant-baseline="middle">${pct.toFixed(pct<10?1:0)}%</text>`);}
    cursor+=pct;
  }
  return `<svg class="resource-donut-svg" viewBox="0 0 360 420" role="img" aria-label="Resource contribution chart">${rings.join('')}<circle cx="${cx}" cy="${cy}" r="54" class="donut-hole"/><text x="${cx}" y="${cy-3}" text-anchor="middle" class="donut-total">${formatCompact(total)}</text><text x="${cx}" y="${cy+15}" text-anchor="middle" class="donut-caption">PER MEMBER</text>${percentages.join('')}${callouts.join('')}</svg>`;
}
function renderResourceVisuals(activities,selected,totals){
  const colorMap=permanentActivityColors();
  $('resourceDonutCharts').innerHTML=selected.map(key=>{const parts=activities.map(a=>({name:a.name,category:a.category,value:a.prorated*positive(a.reward?.[key])})).filter(x=>x.value>0),total=totals[key]||0;return `<article class="resource-donut-card"><h4>${esc(labels[key])}</h4>${total?donutSvg(parts,total,colorMap):'<p>No resource value</p>'}</article>`;}).join('');
  const categories=[['Epic monsters','#efb431'],['Crypts','#66a3ff'],['Citadels','#75c991'],['Tinman','#ef6d55']];
  $('resourceCategoryChart').innerHTML=`<div class="category-legend">${categories.map(([name,color])=>`<span><i style="--legend-color:${color}"></i>${name}</span>`).join('')}</div>${selected.map(key=>{const values=categories.map(([name,color])=>({name,color,value:activities.filter(a=>a.category===name).reduce((sum,a)=>sum+a.prorated*positive(a.reward?.[key]),0)})),total=values.reduce((sum,x)=>sum+x.value,0);return `<div class="category-row"><strong>${esc(labels[key])}</strong><div class="category-bar">${values.map(x=>`<span style="width:${total?x.value/total*100:0}%;background:${x.color}" title="${esc(x.name)}: ${formatCompact(x.value)} (${total?(x.value/total*100).toFixed(1):'0.0'}%)"></span>`).join('')}</div><small>${formatCompact(total)}</small></div>`;}).join('')}`;
}
function renderGoldEconomics(activities){const epics=activities.filter(a=>a.category==='Epic monsters'),colors=permanentActivityColors(),results=epics.map(a=>{const gross=a.prorated*positive(a.reward?.gold),economics=a.economics||{},complete=economics.complete,spent=complete?economics.spent:0;return {...a,gross,spent,net:gross-spent,complete};}),complete=results.filter(x=>x.complete),sort=$('goldEconomicsSort').value,ordered=[...complete].sort((a,b)=>sort==='event'?a.name.localeCompare(b.name):sort==='deficit'?a.net-b.net:b.net-a.net),maxNet=Math.max(1,...complete.map(x=>Math.abs(x.net))),received=complete.reduce((sum,x)=>sum+x.gross,0),spent=complete.reduce((sum,x)=>sum+x.spent,0),net=received-spent;$('goldEconomicsMetrics').innerHTML=[['Total gold net',`${net>=0?'+':'−'}${formatCompact(Math.abs(net))}`,net>=0?'profit':'deficit'],['Gold received',formatCompact(received),''],['Gold spent',formatCompact(spent),''],['Events modeled',`${complete.length} / ${results.length}`,'']].map(([label,value,cls])=>`<article><small>${label}</small><strong class="${cls}">${value}</strong></article>`).join('');$('goldEconomicsChart').innerHTML=ordered.length?`<div class="gold-net-axis"><span>Deficit</span><span>0</span><span>Profit</span></div>${ordered.map(a=>{const width=Math.abs(a.net)/maxNet*50,left=a.net<0?50-width:50;return `<div class="gold-net-chart-row"><strong>${esc(a.name)}</strong><div class="gold-net-track"><i style="left:${left}%;width:${width}%;--activity-color:${colors.get(a.name)}"></i></div><span class="${a.net>=0?'profit':'deficit'}">${a.net>=0?'+':'−'}${formatCompact(Math.abs(a.net))}</span></div>`;}).join('')}`:'<p class="norm-no-resources">Add an efficiency value to display the profit and deficit visual.</p>';$('goldEconomicsRows').innerHTML=results.length?results.map(a=>{const economics=a.economics||{},status=!a.complete?'needs-data':a.net>=0?'profit':'deficit';return `<article class="gold-economics-row ${status}"><div class="gold-economics-event"><i style="--activity-color:${colors.get(a.name)}"></i><strong>${esc(a.name)}</strong><small>${a.complete?`${formatNumber(economics.ratio)} points per gold · ${economics.pct}% gold revive`:'Add Epic points / full gold revive'}</small></div><div><small>Gold received</small><strong>${formatCompact(a.gross)}</strong></div><div><small>Gold spent</small><strong>${a.complete?formatCompact(a.spent):'—'}</strong></div><div><small>Gold ${a.complete?(a.net>=0?'profit':'deficit'):'net'}</small><strong>${a.complete?`${a.net>=0?'+':'−'}${formatCompact(Math.abs(a.net))}`:'Incomplete'}</strong></div></article>`;}).join(''):'<p class="norm-no-resources">Enter an Epic norm to calculate gold economics.</p>';}
function calculatePlanner(){
  const period=plannerPeriod(),recipients=Math.max(1,whole($('clanRecipients').value,100)),contributors=recipients,activities=[];$('customPeriodField').hidden=$('normPeriod').value!=='custom';syncEpicUnits();syncGoldEconomics();applyEpicVisibility();
  const multipliers={B:1e9,M:1e6,K:1e3};
  document.querySelectorAll('.epic-norm-row:not([hidden])').forEach(row=>{const item=normData.epicMonsters.find(x=>x.monster===row.dataset.monster),basis=row.querySelector('.epic-basis').checked?'points':'chests',entered=positive(row.querySelector('.epic-value').value),unit=row.querySelector('.epic-unit').value,value=basis==='points'?entered*multipliers[unit]:entered,chests=basis==='points'?Math.floor(value/item.pointsPerChest):Math.floor(value),points=basis==='points'?value:Math.ceil(chests*item.pointsPerChest),actual=chests*contributors,ratio=parseCompactAmount(row.querySelector('.epic-points-revive').value),pct=Math.min(100,whole(row.querySelector('.epic-gold-pct').value,100)),economicsComplete=ratio>0||pct===0,spent=economicsComplete?points/Math.max(ratio,1)*(pct/100)*(period/item.cadenceDays):0;row.querySelector('.epic-result').innerHTML=chests?basis==='points'?`<strong>${formatNumber(chests)}</strong> chests per player`:`<strong>${formatCompact(points)}</strong> points per player`:'Excluded';if(actual)activities.push({name:item.monster,category:'Epic monsters',cadence:item.cadenceDays,actual,prorated:actual*period/item.cadenceDays,equivalent:basis==='points'?`${formatCompact(points)} points/player`:`${formatNumber(chests)} chests/player`,reward:rewardRecord('EPIC',item.monster),economics:{complete:economicsComplete,ratio,spent,pct}});});
  document.querySelectorAll('.chest-norm-row').forEach(row=>{const [type,...nameParts]=row.querySelector('.chest-norm-select').value.split('|'),name=nameParts.join('|'),count=whole(row.querySelector('.chest-norm-count').value),cadence=Number(row.querySelector('.chest-norm-cadence').value),actual=count*contributors;if(actual)activities.push({name:`${type} · ${name}`,category:type==='CRYPT'?'Crypts':'Citadels',cadence,actual,prorated:actual*period/cadence,equivalent:`${formatNumber(count)} completions/member`,reward:rewardRecord(type,name)});});
  let tinmanPoints=0,tinmanChests=0;const start=Math.min(250,Math.max(1,whole($('tinmanStartLevel').value,1))),summons=Math.min(8,whole($('tinmanSummons').value));for(let i=0;i<summons;i++){const level=Math.min(250,start+i),t=normData.tinman.find(x=>x.level===level);if(!t)continue;tinmanPoints+=t.points;tinmanChests+=t.killChestQuantity;const cadence=normData.tinmanCadenceDays||6;activities.push({name:`Tinman level ${t.level}`,category:'Tinman',cadence,actual:t.killChestQuantity,prorated:t.killChestQuantity*period/cadence,equivalent:`${formatCompact(t.points)} points to defeat`,reward:rewardRecord('EVENT',`${t.chestType} TINMAN`)});}$('tinmanSummary').textContent=tinmanChests?`Levels ${start}–${Math.min(250,start+summons-1)} · ${formatNumber(tinmanChests)} chests received by every member · ${formatCompact(tinmanPoints)} points`:'No Tinmen included.';
  $('normDashboardScope').textContent=`All resource values are per member per ${period}-day ${period===6?'cycle':'planning period'}.`;
  const selected=[...selectedPlannerResources],totals=Object.fromEntries(selected.map(k=>[k,activities.reduce((sum,a)=>sum+a.prorated*positive(a.reward?.[k]),0)]));renderResourceVisuals(activities,selected,totals);if($('enableGoldEconomics').checked)renderGoldEconomics(activities);$('normBreakdownHead').innerHTML=`<tr><th>Event or activity</th>${selected.map(k=>`<th>${esc(labels[k])}<small>amount · share</small></th>`).join('')}</tr>`;$('normBreakdownRows').innerHTML=activities.length?activities.map(a=>`<tr><td><strong>${esc(a.name)}</strong><small>${esc(a.equivalent)}</small></td>${selected.map(k=>{const amount=a.prorated*positive(a.reward?.[k]),pct=totals[k]?amount/totals[k]*100:0;return `<td class="resource-contribution"><strong>${amount?formatCompact(amount):'—'}</strong><small>${amount?`${pct.toFixed(1)}%`:'0%'}</small></td>`;}).join('')}</tr>`).join('')+`<tr class="norm-total-row"><td>Total per member</td>${selected.map(k=>`<td>${formatCompact(totals[k])}<small>100%</small></td>`).join('')}</tr>`:`<tr><td colspan="${1+selected.length}" class="norm-empty-row">Enter a norm above to include it in the plan.</td></tr>`;savePlanner();
}
function restorePlanner(saved=blankPlan()){$('normPeriod').value=saved.period||'6';$('customPeriodDays').value=saved.customPeriodDays||12;$('clanRecipients').value=saved.recipients||saved.contributors||100;$('enableGoldEconomics').checked=!!saved.goldEconomicsEnabled;$('goldEconomicsSort').value=saved.goldEconomicsSort||'profit';selectedPlannerResources.clear();const savedResources=(saved.resources||coreKeys).filter(k=>plannerKeys.includes(k));savedResources.forEach(k=>selectedPlannerResources.add(k));const same=keys=>keys.length===savedResources.length&&keys.every(k=>selectedPlannerResources.has(k));resourcePreset=saved.resourcePreset||(same(coreKeys)?'core':same(growthKeys)?'growth':'all');const savedAll=(saved.allResources||(resourcePreset==='all'?savedResources:plannerKeys)).filter(k=>plannerKeys.includes(k));allResourceSelection=new Set(savedAll);}
function openProfile(id){const profile=profiles.find(x=>x.id===id)||profiles[0],plan=profile.plan||blankPlan();if(!plan.defaultHiddenEpicsApplied){plan.visibleEpics=(plan.visibleEpics||sortedEpics().map(x=>x.monster)).filter(x=>!defaultHiddenEpics.has(x));plan.defaultHiddenEpicsApplied=true;}activeProfileId=profile.id;renderEpicRows(plan.epics);renderEpicVisibility(plan.visibleEpics);const migratedChestNorms=plan.chestNorms||(plan.crypt?[{chestId:`CRYPT|${plan.crypt.chest||'EPIC 35'}`,count:plan.crypt.count??300,cadence:plan.crypt.cadence||6}]:null);renderChestNorms(migratedChestNorms);renderTinman(plan.tinman);restorePlanner(plan);renderPlannerResources();renderProfileSelect();wireValueNavigation();calculatePlanner();}
function profileAction(kind){const current=profiles.find(x=>x.id===activeProfileId);if(kind==='new'){const name=prompt('New clan profile name:','New Clan');if(!name)return;const profile={id:makeId(),name:uniqueProfileName(name),plan:blankPlan()};profiles.push(profile);openProfile(profile.id);}else if(kind==='duplicate'){const profile={id:makeId(),name:uniqueProfileName(`${current.name} Copy`),plan:structuredClone(plannerState())};profiles.push(profile);openProfile(profile.id);}else if(kind==='rename'){const name=prompt('Rename clan profile:',current.name)?.trim();if(name){current.name=uniqueProfileName(name,current.id);renderProfileSelect();saveProfiles();}}else if(kind==='remove'&&profiles.length>1&&confirm(`Remove “${current.name}” from this browser?`)){profiles=profiles.filter(x=>x.id!==activeProfileId);openProfile(profiles[0].id);}saveProfiles();}
function safeFileName(name){return `${String(name||'clan-norms').trim().replace(/[^a-z0-9._-]+/gi,'-').replace(/^-+|-+$/g,'')||'clan-norms'}.norms`;}
function exportProfile(){savePlanner();const profile=profiles.find(x=>x.id===activeProfileId),blob=new Blob([JSON.stringify({format:'tbtoolkit-norms',schemaVersion:1,kind:'clan-norm-profile',exportedAt:new Date().toISOString(),profile:{name:profile.name,plan:profile.plan}},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=safeFileName(profile.name);a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
async function importProfile(file){if(!file)return;try{if(file.size>1_000_000)throw new Error('The file is larger than 1 MB.');const data=JSON.parse(await file.text());if(data?.format!=='tbtoolkit-norms'||data?.kind!=='clan-norm-profile'||!data?.profile?.plan)throw new Error('This is not a valid TB Toolkit .norms file.');const profile={id:makeId(),name:uniqueProfileName(data.profile.name||'Imported Clan'),plan:data.profile.plan};profiles.push(profile);openProfile(profile.id);saveProfiles();}catch(error){alert(error.message||'The .norms file could not be imported.');}finally{$('normsFileInput').value='';}}
function wireValueNavigation(){document.querySelectorAll('.epic-value,.epic-points-revive').forEach(input=>input.addEventListener('keydown',event=>{if(event.key!=='Enter'&&event.key!=='Tab')return;const values=[...document.querySelectorAll('.epic-norm-row:not([hidden]) .epic-value')],efficiencies=[...document.querySelectorAll('.epic-norm-row:not([hidden]) .epic-points-revive')],list=[...values,...efficiencies],index=list.indexOf(input),next=list[(index+(event.shiftKey?-1:1)+list.length)%list.length];event.preventDefault();next.focus();next.select();}));}
function normalizeEpicValue(input){const row=input.closest('.epic-norm-row'),unit=row?.querySelector('.epic-unit');if(!row||!row.querySelector('.epic-basis').checked)return;let value=positive(input.value);if(value>0&&value<1&&unit.value==='B'){value*=1000;unit.value='M';}else if(value>0&&value<1&&unit.value==='M'){value*=1000;unit.value='K';}else if(value>=1000&&unit.value==='K'){value/=1000;unit.value='M';}else if(value>=1000&&unit.value==='M'){value/=1000;unit.value='B';}input.value=String(Number(value.toFixed(6)));}
function initPlanner(){loadProfiles();renderReferences();openProfile(activeProfileId);document.querySelector('.norm-layout').addEventListener('input',calculatePlanner);document.querySelector('.norm-layout').addEventListener('change',calculatePlanner);document.querySelector('.norm-layout').addEventListener('focusin',event=>{if(event.target.matches('input:not([type="checkbox"]):not([type="file"])'))event.target.select();});document.querySelector('.norm-layout').addEventListener('focusout',event=>{if(event.target.classList.contains('epic-value')){normalizeEpicValue(event.target);calculatePlanner();}});$('normProfileSelect').addEventListener('change',event=>{savePlanner();openProfile(event.target.value);});$('newNormProfile').addEventListener('click',()=>profileAction('new'));$('duplicateNormProfile').addEventListener('click',()=>profileAction('duplicate'));$('renameNormProfile').addEventListener('click',()=>profileAction('rename'));$('removeNormProfile').addEventListener('click',()=>profileAction('remove'));$('exportNormProfile').addEventListener('click',exportProfile);$('importNormProfile').addEventListener('click',()=>{$('normsFileInput').value='';$('normsFileInput').click();});$('normsFileInput').addEventListener('change',()=>importProfile($('normsFileInput').files?.[0]));$('addChestNorm').addEventListener('click',()=>{addChestNormRow();calculatePlanner();});$('showAllEpics').addEventListener('click',()=>{document.querySelectorAll('#epicVisibilityOptions input').forEach(x=>x.checked=true);calculatePlanner();});$('hideAllEpics').addEventListener('click',()=>{document.querySelectorAll('#epicVisibilityOptions input').forEach(x=>x.checked=false);calculatePlanner();});document.querySelectorAll('[data-resource-preset]').forEach(button=>button.addEventListener('click',()=>{resourcePreset=button.dataset.resourcePreset;selectedPlannerResources.clear();(resourcePreset==='all'?[...allResourceSelection]:presetKeys(resourcePreset)).forEach(k=>selectedPlannerResources.add(k));renderPlannerResources();calculatePlanner();}));calculatePlanner();}
function resetChestFilters(){$('chestSearch').value='';$('chestTypeFilter').value='';$('chestSort').value='source';columnSort={key:null,direction:null};selectedRewards.clear();$('rewardFilterOptions').querySelectorAll('input').forEach(b=>b.checked=false);updateRewardButton();apply();}
function activateColumnSort(th){const key=th?.dataset?.sortKey;if(!key)return;columnSort=columnSort.key===key?{key,direction:columnSort.direction==='asc'?'desc':'asc'}:{key,direction:'asc'};apply();}
async function init(){try{const [chestRes,normRes]=await Promise.all([fetch('data/chest-data.json',{cache:'no-store'}),fetch('data/norm-planner-data.json',{cache:'no-store'})]);if(!chestRes.ok||!normRes.ok)throw new Error('Planner data could not be loaded.');records=(await chestRes.json()).records||[];normData=await normRes.json();populateFilters();apply();initPlanner();}catch(err){console.error(err);$('epicNormRows').innerHTML='<p class="norm-load-error">Planner data could not be loaded. Refresh the page and try again.</p>';}}
$('chestSearch').addEventListener('input',apply);$('chestTypeFilter').addEventListener('change',apply);$('chestSort').addEventListener('change',()=>{columnSort={key:null,direction:null};apply();});$('chestTableHead').addEventListener('click',e=>activateColumnSort(e.target.closest('.sortable-header')));$('chestTableHead').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activateColumnSort(e.target.closest('.sortable-header'));}});$('rewardFilterButton').addEventListener('click',()=>{const menu=$('rewardFilterMenu'),open=menu.hidden;menu.hidden=!open;$('rewardFilterButton').setAttribute('aria-expanded',String(open));});$('selectAllRewards').addEventListener('click',()=>{resourceKeys.forEach(k=>selectedRewards.add(k));$('rewardFilterOptions').querySelectorAll('input').forEach(b=>b.checked=true);updateRewardButton();apply();});$('clearAllRewards').addEventListener('click',()=>{selectedRewards.clear();$('rewardFilterOptions').querySelectorAll('input').forEach(b=>b.checked=false);updateRewardButton();apply();});document.addEventListener('pointerdown',e=>{const menu=$('rewardFilterMenu'),button=$('rewardFilterButton');if(!menu.hidden&&!menu.contains(e.target)&&!button.contains(e.target)){menu.hidden=true;button.setAttribute('aria-expanded','false');}});$('clearChestSearch').addEventListener('click',()=>{$('chestSearch').value='';apply();$('chestSearch').focus();});$('resetChestFilters').addEventListener('click',resetChestFilters);init();
document.addEventListener('click',event=>{if(event.target.closest('#openEpicEfficiencyHelp')){$('epicEfficiencyHelp').hidden=false;document.body.classList.add('norm-help-open');$('epicEfficiencyHelp').querySelector('[data-efficiency-help-close]').focus();return;}if(event.target.closest('[data-efficiency-help-close]')){$('epicEfficiencyHelp').hidden=true;document.body.classList.remove('norm-help-open');return;}if(event.target.closest('#resetEpicEfficiencies')){document.querySelectorAll('.epic-norm-row').forEach(row=>{row.querySelector('.epic-points-revive').value=epicEfficiencyDefaults[row.dataset.monster]||'';});calculatePlanner();return;}const button=event.target.closest('[data-gold-pct]');if(!button)return;const group=button.closest('.gold-pct-options');group.querySelector('.epic-gold-pct').value=button.dataset.goldPct;group.querySelectorAll('[data-gold-pct]').forEach(option=>option.classList.toggle('is-active',option===button));calculatePlanner();});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('epicEfficiencyHelp').hidden){$('epicEfficiencyHelp').hidden=true;document.body.classList.remove('norm-help-open');}});
})();
